filebeat.inputs:
- type: filestream
  enabled: true
  paths:
  - /var/log/honeypots/*.json
  scan_frequency: 10s
  json:
    keys_under_root: true
    add_error_key: true
    

output.redis:
  hosts: ["redis:6379"]
  key: "honeypot-logs"
  data_type: "list"
  db: 0
  timeout: 5s